//
//  Presenter.swift
//  Dark Matter
//
//  Created by Иван Зайцев on 26.03.2022.
//

import Foundation
import UIKit

protocol UserPresenterDelegate: AnyObject {
    func presentMeasurments(measurments: [Measurement], direction: Direction)
    func presentActivityIndicator(in direction: Direction)
}


enum Direction {
    case up
    case down
}
enum C {
    static let maximumInData = 50
    static let delta = 15
}

typealias PresenterDelegate = UserPresenterDelegate & UIViewController

class UserPresenter {
    
    weak var delegate: PresenterDelegate?
    
    public func getMeasurement(from index: Int) {
        //тут запрос в сеть
        // и в итоге вызываем функцию покажи запрос
        
//        ✅✅✅✅
        self.delegate?.presentMeasurments(measurments: myData, direction: .down)
    }
     
    
    public func updateMeasurement(from index: Int, in direction: Direction) -> [Measurement] {
        // тут типа тоже скачаем и высветим
        print("from index" + "\(index)")
        switch direction {
        case .up:
            return Array(data[index - C.delta...index])
        case .down:
            return Array(data[index...index + C.delta])
        }
       
    }
    
    public func setMyViewDelegate(delegate: PresenterDelegate) {
        self.delegate = delegate
    }
    func scrolledToEnd(direction: Direction) {
        
        guard !isPaginating else { return }
        
        updateData(oldData: myData, pagination: true, in: direction, completion: { [weak self] result in
            switch result {
            case .success(let updatedData):
                
                self?.delegate?.presentMeasurments(measurments: updatedData, direction: direction)
                
            case .failure(_):
                break
            }
        })
        print("activity indicator")
        self.delegate?.presentActivityIndicator(in: direction)
        
        //        switch direction {
        //        case .up:
        //            guard !isPaginating else { return }
        //            updateData(oldData: data, pagination: true, in: .up) { [weak self] result in
        //                switch result {
        //                case .success(let updatedData):
//
//                    self?.delegate?.presentMeasurments(measurments: updatedData, direction: .up)
//
//                case .failure(_):
//                    break
//                }
//            }
////            ✅
//        case .down:
//            guard !isPaginating else { return }
//            updateData(oldData: data, pagination: true, in: .down) { [weak self] result in
//                switch result {
//                case .success(let updatedData):
//
////                    self?.data = updatedData
//                    self?.delegate?.presentMeasurments(measurments: updatedData, direction: .down)
////                    self?.delegate?.pr(.down)
//
//                case .failure(_):
//                    break
//                }
//            }
////            ✅
//        }
    }
    
    var data = [Measurement(measurment: "0 V, no matter", index: 0),
                Measurement(measurment: "1 V, no matter", index: 1),
                Measurement(measurment: "2 V, no matter", index: 2),
                Measurement(measurment: "3 V, no matter", index: 3),
                Measurement(measurment: "4 V, no matter", index: 4),
                Measurement(measurment: "5 V, no matter", index: 5),
                Measurement(measurment: "6 V, no matter", index: 6),
                Measurement(measurment: "7 V, no matter", index: 7),
                Measurement(measurment: "8 V, no matter", index: 8),
                Measurement(measurment: "9 V, no matter", index: 9),
                Measurement(measurment: "10 V, no matter", index: 10),
                Measurement(measurment: "11 V, no matter", index: 11),
                Measurement(measurment: "12 V, no matter", index: 12),
                Measurement(measurment: "13 V, no matter", index: 13),
                Measurement(measurment: "14 V, no matter", index: 14),
                Measurement(measurment: "15 V, no matter", index: 15),
                Measurement(measurment: "16 V, no matter", index: 16),
                Measurement(measurment: "17 V, no matter", index: 17),
                Measurement(measurment: "18 V, no matter", index: 18),
                Measurement(measurment: "19 V, no matter", index: 19),
                Measurement(measurment: "20 V, no matter", index: 20),
                Measurement(measurment: "21 V, no matter", index: 21),
                Measurement(measurment: "22 V, no matter", index: 22),
                Measurement(measurment: "23 V, no matter", index: 23),
                Measurement(measurment: "24 V, no matter", index: 24),
                Measurement(measurment: "25 V, no matter", index: 25),
                Measurement(measurment: "26 V, no matter", index: 26),
                Measurement(measurment: "27 V, no matter", index: 27),
                Measurement(measurment: "28 V, no matter", index: 28),
                Measurement(measurment: "29 V, no matter", index: 29),
                Measurement(measurment: "30 V, no matter", index: 30),
                Measurement(measurment: "31 V, no matter", index: 31),
                Measurement(measurment: "32 V, no matter", index: 32),
                Measurement(measurment: "33 V, no matter", index: 33),
                Measurement(measurment: "34 V, no matter", index: 34),
                Measurement(measurment: "35 V, no matter", index: 35),
                Measurement(measurment: "36 V, no matter", index: 36),
                Measurement(measurment: "37 V, no matter", index: 37),
                Measurement(measurment: "38 V, no matter", index: 38),
                Measurement(measurment: "39 V, no matter", index: 39),
                Measurement(measurment: "40 V, no matter", index: 40),
                Measurement(measurment: "41 V, no matter", index: 41),
                Measurement(measurment: "42 V, no matter", index: 42),
                Measurement(measurment: "43 V, no matter", index: 43),
                Measurement(measurment: "44 V, no matter", index: 44),
                Measurement(measurment: "45 V, no matter", index: 45),
                Measurement(measurment: "46 V, no matter", index: 46),
                Measurement(measurment: "47 V, no matter", index: 47),
                Measurement(measurment: "48 V, no matter", index: 48),
                Measurement(measurment: "49 V, no matter", index: 49),
                Measurement(measurment: "50 V, no matter", index: 50),
                Measurement(measurment: "51 V, no matter", index: 51),
                Measurement(measurment: "52 V, no matter", index: 52),
                Measurement(measurment: "53 V, no matter", index: 53),
                Measurement(measurment: "54 V, no matter", index: 54),
                Measurement(measurment: "55 V, no matter", index: 55),
                Measurement(measurment: "56 V, no matter", index: 56),
                Measurement(measurment: "57 V, no matter", index: 57),
                Measurement(measurment: "58 V, no matter", index: 58),
                Measurement(measurment: "59 V, no matter", index: 59),
                Measurement(measurment: "60 V, no matter", index: 60),
                Measurement(measurment: "61 V, no matter", index: 61),
                Measurement(measurment: "62 V, no matter", index: 62),
                Measurement(measurment: "63 V, no matter", index: 63),
                Measurement(measurment: "64 V, no matter", index: 64),
                Measurement(measurment: "65 V, no matter", index: 65),
                Measurement(measurment: "66 V, no matter", index: 66),
                Measurement(measurment: "67 V, no matter", index: 67),
                Measurement(measurment: "68 V, no matter", index: 68),
                Measurement(measurment: "69 V, no matter", index: 69),
                Measurement(measurment: "70 V, no matter", index: 70),
                Measurement(measurment: "71 V, no matter", index: 71),
                Measurement(measurment: "72 V, no matter", index: 72),
                Measurement(measurment: "73 V, no matter", index: 73),
                Measurement(measurment: "74 V, no matter", index: 74),
                Measurement(measurment: "75 V, no matter", index: 75),
                Measurement(measurment: "76 V, no matter", index: 76),
                Measurement(measurment: "77 V, no matter", index: 77),
                Measurement(measurment: "78 V, no matter", index: 78),
                Measurement(measurment: "79 V, no matter", index: 79),
                Measurement(measurment: "80 V, no matter", index: 80),
                Measurement(measurment: "81 V, no matter", index: 81),
                Measurement(measurment: "82 V, no matter", index: 82),
                Measurement(measurment: "83 V, no matter", index: 83),
                Measurement(measurment: "84 V, no matter", index: 84),
                Measurement(measurment: "85 V, no matter", index: 85),
                Measurement(measurment: "86 V, no matter", index: 86),
                Measurement(measurment: "87 V, no matter", index: 87),
                Measurement(measurment: "88 V, no matter", index: 88),
                Measurement(measurment: "89 V, no matter", index: 89),
                Measurement(measurment: "90 V, no matter", index: 90),
                Measurement(measurment: "91 V, no matter", index: 91),
                Measurement(measurment: "92 V, no matter", index: 92),
                Measurement(measurment: "93 V, no matter", index: 93),
                Measurement(measurment: "94 V, no matter", index: 94),
                Measurement(measurment: "95 V, no matter", index: 95),
                Measurement(measurment: "96 V, no matter", index: 96),
                Measurement(measurment: "97 V, no matter", index: 97),
                Measurement(measurment: "98 V, no matter", index: 98),
                Measurement(measurment: "99 V, no matter", index: 99),
                Measurement(measurment: "100 V, no matter", index: 100),
                Measurement(measurment: "101 V, no matter", index: 101),
                Measurement(measurment: "102 V, no matter", index: 102),
                Measurement(measurment: "103 V, no matter", index: 103),
                Measurement(measurment: "104 V, no matter", index: 104),
                Measurement(measurment: "105 V, no matter", index: 105),
                Measurement(measurment: "106 V, no matter", index: 106),
                Measurement(measurment: "107 V, no matter", index: 107),
                Measurement(measurment: "108 V, no matter", index: 108),
                Measurement(measurment: "109 V, no matter", index: 109),
                Measurement(measurment: "110 V, no matter", index: 110),
                Measurement(measurment: "111 V, no matter", index: 111),
                Measurement(measurment: "112 V, no matter", index: 112),
                Measurement(measurment: "113 V, no matter", index: 113),
                Measurement(measurment: "114 V, no matter", index: 114),
                Measurement(measurment: "115 V, no matter", index: 115),
                Measurement(measurment: "116 V, no matter", index: 116),
                Measurement(measurment: "117 V, no matter", index: 117),
                Measurement(measurment: "118 V, no matter", index: 118),
                Measurement(measurment: "119 V, no matter", index: 119),
                Measurement(measurment: "120 V, no matter", index: 120),
                Measurement(measurment: "121 V, no matter", index: 121),
                Measurement(measurment: "122 V, no matter", index: 122),
                Measurement(measurment: "123 V, no matter", index: 123),
                Measurement(measurment: "124 V, no matter", index: 124),
                Measurement(measurment: "125 V, no matter", index: 125),
                Measurement(measurment: "126 V, no matter", index: 126),
                Measurement(measurment: "127 V, no matter", index: 127),
                Measurement(measurment: "128 V, no matter", index: 128),
                Measurement(measurment: "129 V, no matter", index: 129),
                Measurement(measurment: "130 V, no matter", index: 130),
                Measurement(measurment: "131 V, no matter", index: 131),
                Measurement(measurment: "132 V, no matter", index: 132),
                Measurement(measurment: "133 V, no matter", index: 133),
                Measurement(measurment: "134 V, no matter", index: 134),
                Measurement(measurment: "135 V, no matter", index: 135),
                Measurement(measurment: "136 V, no matter", index: 136),
                Measurement(measurment: "137 V, no matter", index: 137),
                Measurement(measurment: "138 V, no matter", index: 138),
                Measurement(measurment: "139 V, no matter", index: 139),
                Measurement(measurment: "140 V, no matter", index: 140),
                Measurement(measurment: "141 V, no matter", index: 141),
                Measurement(measurment: "142 V, no matter", index: 142),
                Measurement(measurment: "143 V, no matter", index: 143),
                Measurement(measurment: "144 V, no matter", index: 144),
                Measurement(measurment: "145 V, no matter", index: 145),
                Measurement(measurment: "146 V, no matter", index: 146),
                Measurement(measurment: "147 V, no matter", index: 147),
                Measurement(measurment: "148 V, no matter", index: 148),
                Measurement(measurment: "149 V, no matter", index: 149),
                Measurement(measurment: "150 V, no matter", index: 150),
                Measurement(measurment: "151 V, no matter", index: 151),
                Measurement(measurment: "152 V, no matter", index: 152),
                Measurement(measurment: "153 V, no matter", index: 153),
                Measurement(measurment: "154 V, no matter", index: 154),
                Measurement(measurment: "155 V, no matter", index: 155),
                Measurement(measurment: "156 V, no matter", index: 156),
                Measurement(measurment: "157 V, no matter", index: 157),
                Measurement(measurment: "158 V, no matter", index: 158),
                Measurement(measurment: "159 V, no matter", index: 159),
                Measurement(measurment: "160 V, no matter", index: 160),
                Measurement(measurment: "161 V, no matter", index: 161),
                Measurement(measurment: "162 V, no matter", index: 162),
                Measurement(measurment: "163 V, no matter", index: 163),
                Measurement(measurment: "164 V, no matter", index: 164),
                Measurement(measurment: "165 V, no matter", index: 165),
                Measurement(measurment: "166 V, no matter", index: 166),
                Measurement(measurment: "167 V, no matter", index: 167),
                Measurement(measurment: "168 V, no matter", index: 168),
                Measurement(measurment: "169 V, no matter", index: 169),
                Measurement(measurment: "170 V, no matter", index: 170),
                Measurement(measurment: "171 V, no matter", index: 171),
                Measurement(measurment: "172 V, no matter", index: 172),
                Measurement(measurment: "173 V, no matter", index: 173),
                Measurement(measurment: "174 V, no matter", index: 174),
                Measurement(measurment: "175 V, no matter", index: 175),
                Measurement(measurment: "176 V, no matter", index: 176),
                Measurement(measurment: "177 V, no matter", index: 177),
                Measurement(measurment: "178 V, no matter", index: 178),
                Measurement(measurment: "179 V, no matter", index: 179),
                Measurement(measurment: "180 V, no matter", index: 180),
                Measurement(measurment: "181 V, no matter", index: 181),
                Measurement(measurment: "182 V, no matter", index: 182),
                Measurement(measurment: "183 V, no matter", index: 183),
                Measurement(measurment: "184 V, no matter", index: 184),
                Measurement(measurment: "185 V, no matter", index: 185),
                Measurement(measurment: "186 V, no matter", index: 186),
                Measurement(measurment: "187 V, no matter", index: 187),
                Measurement(measurment: "188 V, no matter", index: 188),
                Measurement(measurment: "189 V, no matter", index: 189),
                Measurement(measurment: "190 V, no matter", index: 190),
                Measurement(measurment: "191 V, no matter", index: 191),
                Measurement(measurment: "192 V, no matter", index: 192),
                Measurement(measurment: "193 V, no matter", index: 193),
                Measurement(measurment: "194 V, no matter", index: 194),
                Measurement(measurment: "195 V, no matter", index: 195),
                Measurement(measurment: "196 V, no matter", index: 196),
                Measurement(measurment: "197 V, no matter", index: 197),
                Measurement(measurment: "198 V, no matter", index: 198),
                Measurement(measurment: "199 V, no matter", index: 199),
                Measurement(measurment: "200 V, no matter", index: 200),
                Measurement(measurment: "201 V, no matter", index: 201),
                Measurement(measurment: "202 V, no matter", index: 202),
                Measurement(measurment: "203 V, no matter", index: 203),
                Measurement(measurment: "204 V, no matter", index: 204),
                Measurement(measurment: "205 V, no matter", index: 205),
                Measurement(measurment: "206 V, no matter", index: 206),
                Measurement(measurment: "207 V, no matter", index: 207),
                Measurement(measurment: "208 V, no matter", index: 208),
                Measurement(measurment: "209 V, no matter", index: 209),
                Measurement(measurment: "210 V, no matter", index: 210),
                Measurement(measurment: "211 V, no matter", index: 211),
                Measurement(measurment: "212 V, no matter", index: 212),
                Measurement(measurment: "213 V, no matter", index: 213),
                Measurement(measurment: "214 V, no matter", index: 214),
                Measurement(measurment: "215 V, no matter", index: 215),
                Measurement(measurment: "216 V, no matter", index: 216),
                Measurement(measurment: "217 V, no matter", index: 217),
                Measurement(measurment: "218 V, no matter", index: 218),
                Measurement(measurment: "219 V, no matter", index: 219),
                Measurement(measurment: "220 V, no matter", index: 220),
                Measurement(measurment: "221 V, no matter", index: 221),
                Measurement(measurment: "222 V, no matter", index: 222),
                Measurement(measurment: "223 V, no matter", index: 223),
                Measurement(measurment: "224 V, no matter", index: 224),
                Measurement(measurment: "225 V, no matter", index: 225),
                Measurement(measurment: "226 V, no matter", index: 226),
                Measurement(measurment: "227 V, no matter", index: 227),
                Measurement(measurment: "228 V, no matter", index: 228),
                Measurement(measurment: "229 V, no matter", index: 229),
                Measurement(measurment: "230 V, no matter", index: 230),
                Measurement(measurment: "231 V, no matter", index: 231),
                Measurement(measurment: "232 V, no matter", index: 232),
                Measurement(measurment: "233 V, no matter", index: 233),
                Measurement(measurment: "234 V, no matter", index: 234),
                Measurement(measurment: "235 V, no matter", index: 235),
                Measurement(measurment: "236 V, no matter", index: 236),
                Measurement(measurment: "237 V, no matter", index: 237),
                Measurement(measurment: "238 V, no matter", index: 238),
                Measurement(measurment: "239 V, no matter", index: 239),
                Measurement(measurment: "240 V, no matter", index: 240),
                Measurement(measurment: "241 V, no matter", index: 241),
                Measurement(measurment: "242 V, no matter", index: 242),
                Measurement(measurment: "243 V, no matter", index: 243),
                Measurement(measurment: "244 V, no matter", index: 244),
                Measurement(measurment: "245 V, no matter", index: 245),
                Measurement(measurment: "246 V, no matter", index: 246),
                Measurement(measurment: "247 V, no matter", index: 247),
                Measurement(measurment: "248 V, no matter", index: 248),
                Measurement(measurment: "249 V, no matter", index: 249),
                Measurement(measurment: "250 V, no matter", index: 250),
                Measurement(measurment: "251 V, no matter", index: 251),
                Measurement(measurment: "252 V, no matter", index: 252),
                Measurement(measurment: "253 V, no matter", index: 253),
                Measurement(measurment: "254 V, no matter", index: 254),
                Measurement(measurment: "255 V, no matter", index: 255),
                Measurement(measurment: "256 V, no matter", index: 256),
                Measurement(measurment: "257 V, no matter", index: 257),
                Measurement(measurment: "258 V, no matter", index: 258),
                Measurement(measurment: "259 V, no matter", index: 259),
                Measurement(measurment: "260 V, no matter", index: 260),
                Measurement(measurment: "261 V, no matter", index: 261),
                Measurement(measurment: "262 V, no matter", index: 262),
                Measurement(measurment: "263 V, no matter", index: 263),
                Measurement(measurment: "264 V, no matter", index: 264),
                Measurement(measurment: "265 V, no matter", index: 265),
                Measurement(measurment: "266 V, no matter", index: 266),
                Measurement(measurment: "267 V, no matter", index: 267),
                Measurement(measurment: "268 V, no matter", index: 268),
                Measurement(measurment: "269 V, no matter", index: 269),
                Measurement(measurment: "270 V, no matter", index: 270),
                Measurement(measurment: "271 V, no matter", index: 271),
                Measurement(measurment: "272 V, no matter", index: 272),
                Measurement(measurment: "273 V, no matter", index: 273),
                Measurement(measurment: "274 V, no matter", index: 274),
                Measurement(measurment: "275 V, no matter", index: 275),
                Measurement(measurment: "276 V, no matter", index: 276),
                Measurement(measurment: "277 V, no matter", index: 277),
                Measurement(measurment: "278 V, no matter", index: 278),
                Measurement(measurment: "279 V, no matter", index: 279),
                Measurement(measurment: "280 V, no matter", index: 280),
                Measurement(measurment: "281 V, no matter", index: 281),
                Measurement(measurment: "282 V, no matter", index: 282),
                Measurement(measurment: "283 V, no matter", index: 283),
                Measurement(measurment: "284 V, no matter", index: 284),
                Measurement(measurment: "285 V, no matter", index: 285),
                Measurement(measurment: "286 V, no matter", index: 286),
                Measurement(measurment: "287 V, no matter", index: 287),
                Measurement(measurment: "288 V, no matter", index: 288),
                Measurement(measurment: "289 V, no matter", index: 289),
                Measurement(measurment: "290 V, no matter", index: 290),
                Measurement(measurment: "291 V, no matter", index: 291),
                Measurement(measurment: "292 V, no matter", index: 292),
                Measurement(measurment: "293 V, no matter", index: 293),
                Measurement(measurment: "294 V, no matter", index: 294),
                Measurement(measurment: "295 V, no matter", index: 295),
                Measurement(measurment: "296 V, no matter", index: 296),
                Measurement(measurment: "297 V, no matter", index: 297),
                Measurement(measurment: "298 V, no matter", index: 298),
                Measurement(measurment: "299 V, no matter", index: 299),
                Measurement(measurment: "300 V, no matter", index: 300),
                Measurement(measurment: "301 V, no matter", index: 301),
                Measurement(measurment: "302 V, no matter", index: 302),
                Measurement(measurment: "303 V, no matter", index: 303),
                Measurement(measurment: "304 V, no matter", index: 304),
                Measurement(measurment: "305 V, no matter", index: 305),
                Measurement(measurment: "306 V, no matter", index: 306),
                Measurement(measurment: "307 V, no matter", index: 307),
                Measurement(measurment: "308 V, no matter", index: 308),
                Measurement(measurment: "309 V, no matter", index: 309),
                Measurement(measurment: "310 V, no matter", index: 310),
                Measurement(measurment: "311 V, no matter", index: 311),
                Measurement(measurment: "312 V, no matter", index: 312),
                Measurement(measurment: "313 V, no matter", index: 313),
                Measurement(measurment: "314 V, no matter", index: 314),
                Measurement(measurment: "315 V, no matter", index: 315),
                Measurement(measurment: "316 V, no matter", index: 316),
                Measurement(measurment: "317 V, no matter", index: 317),
                Measurement(measurment: "318 V, no matter", index: 318),
                Measurement(measurment: "319 V, no matter", index: 319),
                Measurement(measurment: "320 V, no matter", index: 320),
                Measurement(measurment: "321 V, no matter", index: 321),
                Measurement(measurment: "322 V, no matter", index: 322),
                Measurement(measurment: "323 V, no matter", index: 323),
                Measurement(measurment: "324 V, no matter", index: 324),
                Measurement(measurment: "325 V, no matter", index: 325),
                Measurement(measurment: "326 V, no matter", index: 326),
                Measurement(measurment: "327 V, no matter", index: 327),
                Measurement(measurment: "328 V, no matter", index: 328),
                Measurement(measurment: "329 V, no matter", index: 329),
                Measurement(measurment: "330 V, no matter", index: 330),
                Measurement(measurment: "331 V, no matter", index: 331),
                Measurement(measurment: "332 V, no matter", index: 332),
                Measurement(measurment: "333 V, no matter", index: 333),
                Measurement(measurment: "334 V, no matter", index: 334),
                Measurement(measurment: "335 V, no matter", index: 335),
                Measurement(measurment: "336 V, no matter", index: 336),
                Measurement(measurment: "337 V, no matter", index: 337),
                Measurement(measurment: "338 V, no matter", index: 338),
                Measurement(measurment: "339 V, no matter", index: 339),
                Measurement(measurment: "340 V, no matter", index: 340),
                Measurement(measurment: "341 V, no matter", index: 341),
                Measurement(measurment: "342 V, no matter", index: 342),
                Measurement(measurment: "343 V, no matter", index: 343),
                Measurement(measurment: "344 V, no matter", index: 344),
                Measurement(measurment: "345 V, no matter", index: 345),
                Measurement(measurment: "346 V, no matter", index: 346),
                Measurement(measurment: "347 V, no matter", index: 347),
                Measurement(measurment: "348 V, no matter", index: 348),
                Measurement(measurment: "349 V, no matter", index: 349),
                Measurement(measurment: "350 V, no matter", index: 350),
                Measurement(measurment: "351 V, no matter", index: 351),
                Measurement(measurment: "352 V, no matter", index: 352),
                Measurement(measurment: "353 V, no matter", index: 353),
                Measurement(measurment: "354 V, no matter", index: 354),
                Measurement(measurment: "355 V, no matter", index: 355),
                Measurement(measurment: "356 V, no matter", index: 356),
                Measurement(measurment: "357 V, no matter", index: 357),
                Measurement(measurment: "358 V, no matter", index: 358),
                Measurement(measurment: "359 V, no matter", index: 359),
                Measurement(measurment: "360 V, no matter", index: 360),
                Measurement(measurment: "361 V, no matter", index: 361),
                Measurement(measurment: "362 V, no matter", index: 362),
                Measurement(measurment: "363 V, no matter", index: 363),
                Measurement(measurment: "364 V, no matter", index: 364),
                Measurement(measurment: "365 V, no matter", index: 365),
                Measurement(measurment: "366 V, no matter", index: 366),
                Measurement(measurment: "367 V, no matter", index: 367),
                Measurement(measurment: "368 V, no matter", index: 368),
                Measurement(measurment: "369 V, no matter", index: 369),
                Measurement(measurment: "370 V, no matter", index: 370),
                Measurement(measurment: "371 V, no matter", index: 371),
                Measurement(measurment: "372 V, no matter", index: 372),
                Measurement(measurment: "373 V, no matter", index: 373),
                Measurement(measurment: "374 V, no matter", index: 374),
                Measurement(measurment: "375 V, no matter", index: 375),
                Measurement(measurment: "376 V, no matter", index: 376),
                Measurement(measurment: "377 V, no matter", index: 377),
                Measurement(measurment: "378 V, no matter", index: 378),
                Measurement(measurment: "379 V, no matter", index: 379),
                Measurement(measurment: "380 V, no matter", index: 380),
                Measurement(measurment: "381 V, no matter", index: 381),
                Measurement(measurment: "382 V, no matter", index: 382),
                Measurement(measurment: "383 V, no matter", index: 383),
                Measurement(measurment: "384 V, no matter", index: 384),
                Measurement(measurment: "385 V, no matter", index: 385),
                Measurement(measurment: "386 V, no matter", index: 386),
                Measurement(measurment: "387 V, no matter", index: 387),
                Measurement(measurment: "388 V, no matter", index: 388),
                Measurement(measurment: "389 V, no matter", index: 389),
                Measurement(measurment: "390 V, no matter", index: 390),
                Measurement(measurment: "391 V, no matter", index: 391),
                Measurement(measurment: "392 V, no matter", index: 392),
                Measurement(measurment: "393 V, no matter", index: 393),
                Measurement(measurment: "394 V, no matter", index: 394),
                Measurement(measurment: "395 V, no matter", index: 395),
                Measurement(measurment: "396 V, no matter", index: 396),
                Measurement(measurment: "397 V, no matter", index: 397),
                Measurement(measurment: "398 V, no matter", index: 398),
                Measurement(measurment: "399 V, no matter", index: 399),
                Measurement(measurment: "400 V, no matter", index: 400),
                Measurement(measurment: "401 V, no matter", index: 401),
                Measurement(measurment: "402 V, no matter", index: 402),
                Measurement(measurment: "403 V, no matter", index: 403),
                Measurement(measurment: "404 V, no matter", index: 404),
                Measurement(measurment: "405 V, no matter", index: 405),
                Measurement(measurment: "406 V, no matter", index: 406),
                Measurement(measurment: "407 V, no matter", index: 407),
                Measurement(measurment: "408 V, no matter", index: 408),
                Measurement(measurment: "409 V, no matter", index: 409),
                Measurement(measurment: "410 V, no matter", index: 410),
                Measurement(measurment: "411 V, no matter", index: 411),
                Measurement(measurment: "412 V, no matter", index: 412),
                Measurement(measurment: "413 V, no matter", index: 413),
                Measurement(measurment: "414 V, no matter", index: 414),
                Measurement(measurment: "415 V, no matter", index: 415),
                Measurement(measurment: "416 V, no matter", index: 416),
                Measurement(measurment: "417 V, no matter", index: 417),
                Measurement(measurment: "418 V, no matter", index: 418),
                Measurement(measurment: "419 V, no matter", index: 419),
                Measurement(measurment: "420 V, no matter", index: 420),
                Measurement(measurment: "421 V, no matter", index: 421),
                Measurement(measurment: "422 V, no matter", index: 422),
                Measurement(measurment: "423 V, no matter", index: 423),
                Measurement(measurment: "424 V, no matter", index: 424),
                Measurement(measurment: "425 V, no matter", index: 425),
                Measurement(measurment: "426 V, no matter", index: 426),
                Measurement(measurment: "427 V, no matter", index: 427),
                Measurement(measurment: "428 V, no matter", index: 428),
                Measurement(measurment: "429 V, no matter", index: 429),
                Measurement(measurment: "430 V, no matter", index: 430),
                Measurement(measurment: "431 V, no matter", index: 431),
                Measurement(measurment: "432 V, no matter", index: 432),
                Measurement(measurment: "433 V, no matter", index: 433),
                Measurement(measurment: "434 V, no matter", index: 434),
                Measurement(measurment: "435 V, no matter", index: 435),
                Measurement(measurment: "436 V, no matter", index: 436),
                Measurement(measurment: "437 V, no matter", index: 437),
                Measurement(measurment: "438 V, no matter", index: 438),
                Measurement(measurment: "439 V, no matter", index: 439),
                Measurement(measurment: "440 V, no matter", index: 440),
                Measurement(measurment: "441 V, no matter", index: 441),
                Measurement(measurment: "442 V, no matter", index: 442),
                Measurement(measurment: "443 V, no matter", index: 443),
                Measurement(measurment: "444 V, no matter", index: 444),
                Measurement(measurment: "445 V, no matter", index: 445),
                Measurement(measurment: "446 V, no matter", index: 446),
                Measurement(measurment: "447 V, no matter", index: 447),
                Measurement(measurment: "448 V, no matter", index: 448),
                Measurement(measurment: "449 V, no matter", index: 449),
                Measurement(measurment: "450 V, no matter", index: 450),
                Measurement(measurment: "451 V, no matter", index: 451),
                Measurement(measurment: "452 V, no matter", index: 452),
                Measurement(measurment: "453 V, no matter", index: 453),
                Measurement(measurment: "454 V, no matter", index: 454),
                Measurement(measurment: "455 V, no matter", index: 455),
                Measurement(measurment: "456 V, no matter", index: 456),
                Measurement(measurment: "457 V, no matter", index: 457),
                Measurement(measurment: "458 V, no matter", index: 458),
                Measurement(measurment: "459 V, no matter", index: 459),
                Measurement(measurment: "460 V, no matter", index: 460),
                Measurement(measurment: "461 V, no matter", index: 461),
                Measurement(measurment: "462 V, no matter", index: 462),
                Measurement(measurment: "463 V, no matter", index: 463),
                Measurement(measurment: "464 V, no matter", index: 464),
                Measurement(measurment: "465 V, no matter", index: 465),
                Measurement(measurment: "466 V, no matter", index: 466),
                Measurement(measurment: "467 V, no matter", index: 467),
                Measurement(measurment: "468 V, no matter", index: 468),
                Measurement(measurment: "469 V, no matter", index: 469),
                Measurement(measurment: "470 V, no matter", index: 470),
                Measurement(measurment: "471 V, no matter", index: 471),
                Measurement(measurment: "472 V, no matter", index: 472),
                Measurement(measurment: "473 V, no matter", index: 473),
                Measurement(measurment: "474 V, no matter", index: 474),
                Measurement(measurment: "475 V, no matter", index: 475),
                Measurement(measurment: "476 V, no matter", index: 476),
                Measurement(measurment: "477 V, no matter", index: 477),
                Measurement(measurment: "478 V, no matter", index: 478),
                Measurement(measurment: "479 V, no matter", index: 479),
                Measurement(measurment: "480 V, no matter", index: 480),
                Measurement(measurment: "481 V, no matter", index: 481),
                Measurement(measurment: "482 V, no matter", index: 482),
                Measurement(measurment: "483 V, no matter", index: 483),
                Measurement(measurment: "484 V, no matter", index: 484),
                Measurement(measurment: "485 V, no matter", index: 485),
                Measurement(measurment: "486 V, no matter", index: 486),
                Measurement(measurment: "487 V, no matter", index: 487),
                Measurement(measurment: "488 V, no matter", index: 488),
                Measurement(measurment: "489 V, no matter", index: 489),
                Measurement(measurment: "490 V, no matter", index: 490),
                Measurement(measurment: "491 V, no matter", index: 491),
                Measurement(measurment: "492 V, no matter", index: 492),
                Measurement(measurment: "493 V, no matter", index: 493),
                Measurement(measurment: "494 V, no matter", index: 494),
                Measurement(measurment: "495 V, no matter", index: 495),
                Measurement(measurment: "496 V, no matter", index: 496),
                Measurement(measurment: "497 V, no matter", index: 497),
                Measurement(measurment: "498 V, no matter", index: 498),
                Measurement(measurment: "499 V, no matter", index: 499),
                Measurement(measurment: "500 V, no matter", index: 500),
                Measurement(measurment: "501 V, no matter", index: 501),
                Measurement(measurment: "502 V, no matter", index: 502),
                Measurement(measurment: "503 V, no matter", index: 503),
                Measurement(measurment: "504 V, no matter", index: 504),
                Measurement(measurment: "505 V, no matter", index: 505),
                Measurement(measurment: "506 V, no matter", index: 506),
                Measurement(measurment: "507 V, no matter", index: 507),
                Measurement(measurment: "508 V, no matter", index: 508),
                Measurement(measurment: "509 V, no matter", index: 509),
                Measurement(measurment: "510 V, no matter", index: 510),
                Measurement(measurment: "511 V, no matter", index: 511),
                Measurement(measurment: "512 V, no matter", index: 512),
                Measurement(measurment: "513 V, no matter", index: 513),
                Measurement(measurment: "514 V, no matter", index: 514),
                Measurement(measurment: "515 V, no matter", index: 515),
                Measurement(measurment: "516 V, no matter", index: 516),
                Measurement(measurment: "517 V, no matter", index: 517),
                Measurement(measurment: "518 V, no matter", index: 518),
                Measurement(measurment: "519 V, no matter", index: 519),
                Measurement(measurment: "520 V, no matter", index: 520),
                Measurement(measurment: "521 V, no matter", index: 521),
                Measurement(measurment: "522 V, no matter", index: 522),
                Measurement(measurment: "523 V, no matter", index: 523),
                Measurement(measurment: "524 V, no matter", index: 524),
                Measurement(measurment: "525 V, no matter", index: 525),
                Measurement(measurment: "526 V, no matter", index: 526),
                Measurement(measurment: "527 V, no matter", index: 527),
                Measurement(measurment: "528 V, no matter", index: 528),
                Measurement(measurment: "529 V, no matter", index: 529),
                Measurement(measurment: "530 V, no matter", index: 530),
                Measurement(measurment: "531 V, no matter", index: 531),
                Measurement(measurment: "532 V, no matter", index: 532),
                Measurement(measurment: "533 V, no matter", index: 533),
                Measurement(measurment: "534 V, no matter", index: 534),
                Measurement(measurment: "535 V, no matter", index: 535),
                Measurement(measurment: "536 V, no matter", index: 536),
                Measurement(measurment: "537 V, no matter", index: 537),
                Measurement(measurment: "538 V, no matter", index: 538),
                Measurement(measurment: "539 V, no matter", index: 539),
                Measurement(measurment: "540 V, no matter", index: 540),
                Measurement(measurment: "541 V, no matter", index: 541),
                Measurement(measurment: "542 V, no matter", index: 542),
                Measurement(measurment: "543 V, no matter", index: 543),
                Measurement(measurment: "544 V, no matter", index: 544),
                Measurement(measurment: "545 V, no matter", index: 545),
                Measurement(measurment: "546 V, no matter", index: 546),
                Measurement(measurment: "547 V, no matter", index: 547),
                Measurement(measurment: "548 V, no matter", index: 548),
                Measurement(measurment: "549 V, no matter", index: 549),
                Measurement(measurment: "550 V, no matter", index: 550),
                Measurement(measurment: "551 V, no matter", index: 551),
                Measurement(measurment: "552 V, no matter", index: 552),
                Measurement(measurment: "553 V, no matter", index: 553),
                Measurement(measurment: "554 V, no matter", index: 554),
                Measurement(measurment: "555 V, no matter", index: 555),
                Measurement(measurment: "556 V, no matter", index: 556),
                Measurement(measurment: "557 V, no matter", index: 557),
                Measurement(measurment: "558 V, no matter", index: 558),
                Measurement(measurment: "559 V, no matter", index: 559),
                Measurement(measurment: "560 V, no matter", index: 560),
                Measurement(measurment: "561 V, no matter", index: 561),
                Measurement(measurment: "562 V, no matter", index: 562),
                Measurement(measurment: "563 V, no matter", index: 563),
                Measurement(measurment: "564 V, no matter", index: 564),
                Measurement(measurment: "565 V, no matter", index: 565),
                Measurement(measurment: "566 V, no matter", index: 566),
                Measurement(measurment: "567 V, no matter", index: 567),
                Measurement(measurment: "568 V, no matter", index: 568),
                Measurement(measurment: "569 V, no matter", index: 569),
                Measurement(measurment: "570 V, no matter", index: 570),
                Measurement(measurment: "571 V, no matter", index: 571),
                Measurement(measurment: "572 V, no matter", index: 572),
                Measurement(measurment: "573 V, no matter", index: 573),
                Measurement(measurment: "574 V, no matter", index: 574),
                Measurement(measurment: "575 V, no matter", index: 575),
                Measurement(measurment: "576 V, no matter", index: 576),
                Measurement(measurment: "577 V, no matter", index: 577),
                Measurement(measurment: "578 V, no matter", index: 578),
                Measurement(measurment: "579 V, no matter", index: 579),
                Measurement(measurment: "580 V, no matter", index: 580),
                Measurement(measurment: "581 V, no matter", index: 581),
                Measurement(measurment: "582 V, no matter", index: 582),
                Measurement(measurment: "583 V, no matter", index: 583),
                Measurement(measurment: "584 V, no matter", index: 584),
                Measurement(measurment: "585 V, no matter", index: 585),
                Measurement(measurment: "586 V, no matter", index: 586),
                Measurement(measurment: "587 V, no matter", index: 587),
                Measurement(measurment: "588 V, no matter", index: 588),
                Measurement(measurment: "589 V, no matter", index: 589),
                Measurement(measurment: "590 V, no matter", index: 590),
                Measurement(measurment: "591 V, no matter", index: 591),
                Measurement(measurment: "592 V, no matter", index: 592),
                Measurement(measurment: "593 V, no matter", index: 593),
                Measurement(measurment: "594 V, no matter", index: 594),
                Measurement(measurment: "595 V, no matter", index: 595),
                Measurement(measurment: "596 V, no matter", index: 596),
                Measurement(measurment: "597 V, no matter", index: 597),
                Measurement(measurment: "598 V, no matter", index: 598),
                Measurement(measurment: "599 V, no matter", index: 599),
                Measurement(measurment: "600 V, no matter", index: 600),
                Measurement(measurment: "601 V, no matter", index: 601),
                Measurement(measurment: "602 V, no matter", index: 602),
                Measurement(measurment: "603 V, no matter", index: 603),
                Measurement(measurment: "604 V, no matter", index: 604),
                Measurement(measurment: "605 V, no matter", index: 605),
                Measurement(measurment: "606 V, no matter", index: 606),
                Measurement(measurment: "607 V, no matter", index: 607),
                Measurement(measurment: "608 V, no matter", index: 608),
                Measurement(measurment: "609 V, no matter", index: 609),
                Measurement(measurment: "610 V, no matter", index: 610),
                Measurement(measurment: "611 V, no matter", index: 611),
                Measurement(measurment: "612 V, no matter", index: 612),
                Measurement(measurment: "613 V, no matter", index: 613),
                Measurement(measurment: "614 V, no matter", index: 614),
                Measurement(measurment: "615 V, no matter", index: 615),
                Measurement(measurment: "616 V, no matter", index: 616),
                Measurement(measurment: "617 V, no matter", index: 617),
                Measurement(measurment: "618 V, no matter", index: 618),
                Measurement(measurment: "619 V, no matter", index: 619),
                Measurement(measurment: "620 V, no matter", index: 620),
                Measurement(measurment: "621 V, no matter", index: 621),
                Measurement(measurment: "622 V, no matter", index: 622),
                Measurement(measurment: "623 V, no matter", index: 623),
                Measurement(measurment: "624 V, no matter", index: 624),
                Measurement(measurment: "625 V, no matter", index: 625),
                Measurement(measurment: "626 V, no matter", index: 626),
                Measurement(measurment: "627 V, no matter", index: 627),
                Measurement(measurment: "628 V, no matter", index: 628),
                Measurement(measurment: "629 V, no matter", index: 629),
                Measurement(measurment: "630 V, no matter", index: 630),
                Measurement(measurment: "631 V, no matter", index: 631),
                Measurement(measurment: "632 V, no matter", index: 632),
                Measurement(measurment: "633 V, no matter", index: 633),
                Measurement(measurment: "634 V, no matter", index: 634),
                Measurement(measurment: "635 V, no matter", index: 635),
                Measurement(measurment: "636 V, no matter", index: 636),
                Measurement(measurment: "637 V, no matter", index: 637),
                Measurement(measurment: "638 V, no matter", index: 638),
                Measurement(measurment: "639 V, no matter", index: 639),
                Measurement(measurment: "640 V, no matter", index: 640),
                Measurement(measurment: "641 V, no matter", index: 641),
                Measurement(measurment: "642 V, no matter", index: 642),
                Measurement(measurment: "643 V, no matter", index: 643),
                Measurement(measurment: "644 V, no matter", index: 644),
                Measurement(measurment: "645 V, no matter", index: 645),
                Measurement(measurment: "646 V, no matter", index: 646),
                Measurement(measurment: "647 V, no matter", index: 647),
                Measurement(measurment: "648 V, no matter", index: 648),
                Measurement(measurment: "649 V, no matter", index: 649),
                Measurement(measurment: "650 V, no matter", index: 650),
                Measurement(measurment: "651 V, no matter", index: 651),
                Measurement(measurment: "652 V, no matter", index: 652),
                Measurement(measurment: "653 V, no matter", index: 653),
                Measurement(measurment: "654 V, no matter", index: 654),
                Measurement(measurment: "655 V, no matter", index: 655),
                Measurement(measurment: "656 V, no matter", index: 656),
                Measurement(measurment: "657 V, no matter", index: 657),
                Measurement(measurment: "658 V, no matter", index: 658),
                Measurement(measurment: "659 V, no matter", index: 659),
                Measurement(measurment: "660 V, no matter", index: 660),
                Measurement(measurment: "661 V, no matter", index: 661),
                Measurement(measurment: "662 V, no matter", index: 662),
                Measurement(measurment: "663 V, no matter", index: 663),
                Measurement(measurment: "664 V, no matter", index: 664),
                Measurement(measurment: "665 V, no matter", index: 665),
                Measurement(measurment: "666 V, no matter", index: 666),
                Measurement(measurment: "667 V, no matter", index: 667),
                Measurement(measurment: "668 V, no matter", index: 668),
                Measurement(measurment: "669 V, no matter", index: 669),
                Measurement(measurment: "670 V, no matter", index: 670),
                Measurement(measurment: "671 V, no matter", index: 671),
                Measurement(measurment: "672 V, no matter", index: 672),
                Measurement(measurment: "673 V, no matter", index: 673),
                Measurement(measurment: "674 V, no matter", index: 674),
                Measurement(measurment: "675 V, no matter", index: 675),
                Measurement(measurment: "676 V, no matter", index: 676),
                Measurement(measurment: "677 V, no matter", index: 677),
                Measurement(measurment: "678 V, no matter", index: 678),
                Measurement(measurment: "679 V, no matter", index: 679),
                Measurement(measurment: "680 V, no matter", index: 680),
                Measurement(measurment: "681 V, no matter", index: 681),
                Measurement(measurment: "682 V, no matter", index: 682),
                Measurement(measurment: "683 V, no matter", index: 683),
                Measurement(measurment: "684 V, no matter", index: 684),
                Measurement(measurment: "685 V, no matter", index: 685),
                Measurement(measurment: "686 V, no matter", index: 686),
                Measurement(measurment: "687 V, no matter", index: 687),
                Measurement(measurment: "688 V, no matter", index: 688),
                Measurement(measurment: "689 V, no matter", index: 689),
                Measurement(measurment: "690 V, no matter", index: 690),
                Measurement(measurment: "691 V, no matter", index: 691),
                Measurement(measurment: "692 V, no matter", index: 692),
                Measurement(measurment: "693 V, no matter", index: 693),
                Measurement(measurment: "694 V, no matter", index: 694),
                Measurement(measurment: "695 V, no matter", index: 695),
                Measurement(measurment: "696 V, no matter", index: 696),
                Measurement(measurment: "697 V, no matter", index: 697),
                Measurement(measurment: "698 V, no matter", index: 698),
                Measurement(measurment: "699 V, no matter", index: 699),
                Measurement(measurment: "700 V, no matter", index: 700),
                Measurement(measurment: "701 V, no matter", index: 701),
                Measurement(measurment: "702 V, no matter", index: 702),
                Measurement(measurment: "703 V, no matter", index: 703),
                Measurement(measurment: "704 V, no matter", index: 704),
                Measurement(measurment: "705 V, no matter", index: 705),
                Measurement(measurment: "706 V, no matter", index: 706),
                Measurement(measurment: "707 V, no matter", index: 707),
                Measurement(measurment: "708 V, no matter", index: 708),
                Measurement(measurment: "709 V, no matter", index: 709),
                Measurement(measurment: "710 V, no matter", index: 710),
                Measurement(measurment: "711 V, no matter", index: 711),
                Measurement(measurment: "712 V, no matter", index: 712),
                Measurement(measurment: "713 V, no matter", index: 713),
                Measurement(measurment: "714 V, no matter", index: 714),
                Measurement(measurment: "715 V, no matter", index: 715),
                Measurement(measurment: "716 V, no matter", index: 716),
                Measurement(measurment: "717 V, no matter", index: 717),
                Measurement(measurment: "718 V, no matter", index: 718),
                Measurement(measurment: "719 V, no matter", index: 719),
                Measurement(measurment: "720 V, no matter", index: 720),
                Measurement(measurment: "721 V, no matter", index: 721),
                Measurement(measurment: "722 V, no matter", index: 722),
                Measurement(measurment: "723 V, no matter", index: 723),
                Measurement(measurment: "724 V, no matter", index: 724),
                Measurement(measurment: "725 V, no matter", index: 725),
                Measurement(measurment: "726 V, no matter", index: 726),
                Measurement(measurment: "727 V, no matter", index: 727),
                Measurement(measurment: "728 V, no matter", index: 728),
                Measurement(measurment: "729 V, no matter", index: 729),
                Measurement(measurment: "730 V, no matter", index: 730),
                Measurement(measurment: "731 V, no matter", index: 731),
                Measurement(measurment: "732 V, no matter", index: 732),
                Measurement(measurment: "733 V, no matter", index: 733),
                Measurement(measurment: "734 V, no matter", index: 734),
                Measurement(measurment: "735 V, no matter", index: 735),
                Measurement(measurment: "736 V, no matter", index: 736),
                Measurement(measurment: "737 V, no matter", index: 737),
                Measurement(measurment: "738 V, no matter", index: 738),
                Measurement(measurment: "739 V, no matter", index: 739),
                Measurement(measurment: "740 V, no matter", index: 740),
                Measurement(measurment: "741 V, no matter", index: 741),
                Measurement(measurment: "742 V, no matter", index: 742),
                Measurement(measurment: "743 V, no matter", index: 743),
                Measurement(measurment: "744 V, no matter", index: 744),
                Measurement(measurment: "745 V, no matter", index: 745),
                Measurement(measurment: "746 V, no matter", index: 746),
                Measurement(measurment: "747 V, no matter", index: 747),
                Measurement(measurment: "748 V, no matter", index: 748),
                Measurement(measurment: "749 V, no matter", index: 749),
                Measurement(measurment: "750 V, no matter", index: 750),
                Measurement(measurment: "751 V, no matter", index: 751),
                Measurement(measurment: "752 V, no matter", index: 752),
                Measurement(measurment: "753 V, no matter", index: 753),
                Measurement(measurment: "754 V, no matter", index: 754),
                Measurement(measurment: "755 V, no matter", index: 755),
                Measurement(measurment: "756 V, no matter", index: 756),
                Measurement(measurment: "757 V, no matter", index: 757),
                Measurement(measurment: "758 V, no matter", index: 758),
                Measurement(measurment: "759 V, no matter", index: 759),
                Measurement(measurment: "760 V, no matter", index: 760),
                Measurement(measurment: "761 V, no matter", index: 761),
                Measurement(measurment: "762 V, no matter", index: 762),
                Measurement(measurment: "763 V, no matter", index: 763),
                Measurement(measurment: "764 V, no matter", index: 764),
                Measurement(measurment: "765 V, no matter", index: 765),
                Measurement(measurment: "766 V, no matter", index: 766),
                Measurement(measurment: "767 V, no matter", index: 767),
                Measurement(measurment: "768 V, no matter", index: 768),
                Measurement(measurment: "769 V, no matter", index: 769),
                Measurement(measurment: "770 V, no matter", index: 770),
                Measurement(measurment: "771 V, no matter", index: 771),
                Measurement(measurment: "772 V, no matter", index: 772),
                Measurement(measurment: "773 V, no matter", index: 773),
                Measurement(measurment: "774 V, no matter", index: 774),
                Measurement(measurment: "775 V, no matter", index: 775),
                Measurement(measurment: "776 V, no matter", index: 776),
                Measurement(measurment: "777 V, no matter", index: 777),
                Measurement(measurment: "778 V, no matter", index: 778),
                Measurement(measurment: "779 V, no matter", index: 779),
                Measurement(measurment: "780 V, no matter", index: 780),
                Measurement(measurment: "781 V, no matter", index: 781),
                Measurement(measurment: "782 V, no matter", index: 782),
                Measurement(measurment: "783 V, no matter", index: 783),
                Measurement(measurment: "784 V, no matter", index: 784),
                Measurement(measurment: "785 V, no matter", index: 785),
                Measurement(measurment: "786 V, no matter", index: 786),
                Measurement(measurment: "787 V, no matter", index: 787),
                Measurement(measurment: "788 V, no matter", index: 788),
                Measurement(measurment: "789 V, no matter", index: 789),
                Measurement(measurment: "790 V, no matter", index: 790),
                Measurement(measurment: "791 V, no matter", index: 791),
                Measurement(measurment: "792 V, no matter", index: 792),
                Measurement(measurment: "793 V, no matter", index: 793),
                Measurement(measurment: "794 V, no matter", index: 794),
                Measurement(measurment: "795 V, no matter", index: 795),
                Measurement(measurment: "796 V, no matter", index: 796),
                Measurement(measurment: "797 V, no matter", index: 797),
                Measurement(measurment: "798 V, no matter", index: 798),
                Measurement(measurment: "799 V, no matter", index: 799),
                Measurement(measurment: "800 V, no matter", index: 800),
                Measurement(measurment: "801 V, no matter", index: 801),
                Measurement(measurment: "802 V, no matter", index: 802),
                Measurement(measurment: "803 V, no matter", index: 803),
                Measurement(measurment: "804 V, no matter", index: 804),
                Measurement(measurment: "805 V, no matter", index: 805),
                Measurement(measurment: "806 V, no matter", index: 806),
                Measurement(measurment: "807 V, no matter", index: 807),
                Measurement(measurment: "808 V, no matter", index: 808),
                Measurement(measurment: "809 V, no matter", index: 809),
                Measurement(measurment: "810 V, no matter", index: 810),
                Measurement(measurment: "811 V, no matter", index: 811),
                Measurement(measurment: "812 V, no matter", index: 812),
                Measurement(measurment: "813 V, no matter", index: 813),
                Measurement(measurment: "814 V, no matter", index: 814),
                Measurement(measurment: "815 V, no matter", index: 815),
                Measurement(measurment: "816 V, no matter", index: 816),
                Measurement(measurment: "817 V, no matter", index: 817),
                Measurement(measurment: "818 V, no matter", index: 818),
                Measurement(measurment: "819 V, no matter", index: 819),
                Measurement(measurment: "820 V, no matter", index: 820),
                Measurement(measurment: "821 V, no matter", index: 821),
                Measurement(measurment: "822 V, no matter", index: 822),
                Measurement(measurment: "823 V, no matter", index: 823),
                Measurement(measurment: "824 V, no matter", index: 824),
                Measurement(measurment: "825 V, no matter", index: 825),
                Measurement(measurment: "826 V, no matter", index: 826),
                Measurement(measurment: "827 V, no matter", index: 827),
                Measurement(measurment: "828 V, no matter", index: 828),
                Measurement(measurment: "829 V, no matter", index: 829),
                Measurement(measurment: "830 V, no matter", index: 830),
                Measurement(measurment: "831 V, no matter", index: 831),
                Measurement(measurment: "832 V, no matter", index: 832),
                Measurement(measurment: "833 V, no matter", index: 833),
                Measurement(measurment: "834 V, no matter", index: 834),
                Measurement(measurment: "835 V, no matter", index: 835),
                Measurement(measurment: "836 V, no matter", index: 836),
                Measurement(measurment: "837 V, no matter", index: 837),
                Measurement(measurment: "838 V, no matter", index: 838),
                Measurement(measurment: "839 V, no matter", index: 839),
                Measurement(measurment: "840 V, no matter", index: 840),
                Measurement(measurment: "841 V, no matter", index: 841),
                Measurement(measurment: "842 V, no matter", index: 842),
                Measurement(measurment: "843 V, no matter", index: 843),
                Measurement(measurment: "844 V, no matter", index: 844),
                Measurement(measurment: "845 V, no matter", index: 845),
                Measurement(measurment: "846 V, no matter", index: 846),
                Measurement(measurment: "847 V, no matter", index: 847),
                Measurement(measurment: "848 V, no matter", index: 848),
                Measurement(measurment: "849 V, no matter", index: 849),
                Measurement(measurment: "850 V, no matter", index: 850),
                Measurement(measurment: "851 V, no matter", index: 851),
                Measurement(measurment: "852 V, no matter", index: 852),
                Measurement(measurment: "853 V, no matter", index: 853),
                Measurement(measurment: "854 V, no matter", index: 854),
                Measurement(measurment: "855 V, no matter", index: 855),
                Measurement(measurment: "856 V, no matter", index: 856),
                Measurement(measurment: "857 V, no matter", index: 857),
                Measurement(measurment: "858 V, no matter", index: 858),
                Measurement(measurment: "859 V, no matter", index: 859),
                Measurement(measurment: "860 V, no matter", index: 860),
                Measurement(measurment: "861 V, no matter", index: 861),
                Measurement(measurment: "862 V, no matter", index: 862),
                Measurement(measurment: "863 V, no matter", index: 863),
                Measurement(measurment: "864 V, no matter", index: 864),
                Measurement(measurment: "865 V, no matter", index: 865),
                Measurement(measurment: "866 V, no matter", index: 866),
                Measurement(measurment: "867 V, no matter", index: 867),
                Measurement(measurment: "868 V, no matter", index: 868),
                Measurement(measurment: "869 V, no matter", index: 869),
                Measurement(measurment: "870 V, no matter", index: 870),
                Measurement(measurment: "871 V, no matter", index: 871),
                Measurement(measurment: "872 V, no matter", index: 872),
                Measurement(measurment: "873 V, no matter", index: 873),
                Measurement(measurment: "874 V, no matter", index: 874),
                Measurement(measurment: "875 V, no matter", index: 875),
                Measurement(measurment: "876 V, no matter", index: 876),
                Measurement(measurment: "877 V, no matter", index: 877),
                Measurement(measurment: "878 V, no matter", index: 878),
                Measurement(measurment: "879 V, no matter", index: 879),
                Measurement(measurment: "880 V, no matter", index: 880),
                Measurement(measurment: "881 V, no matter", index: 881),
                Measurement(measurment: "882 V, no matter", index: 882),
                Measurement(measurment: "883 V, no matter", index: 883),
                Measurement(measurment: "884 V, no matter", index: 884),
                Measurement(measurment: "885 V, no matter", index: 885),
                Measurement(measurment: "886 V, no matter", index: 886),
                Measurement(measurment: "887 V, no matter", index: 887),
                Measurement(measurment: "888 V, no matter", index: 888),
                Measurement(measurment: "889 V, no matter", index: 889),
                Measurement(measurment: "890 V, no matter", index: 890),
                Measurement(measurment: "891 V, no matter", index: 891),
                Measurement(measurment: "892 V, no matter", index: 892),
                Measurement(measurment: "893 V, no matter", index: 893),
                Measurement(measurment: "894 V, no matter", index: 894),
                Measurement(measurment: "895 V, no matter", index: 895),
                Measurement(measurment: "896 V, no matter", index: 896),
                Measurement(measurment: "897 V, no matter", index: 897),
                Measurement(measurment: "898 V, no matter", index: 898),
                Measurement(measurment: "899 V, no matter", index: 899),
                Measurement(measurment: "900 V, no matter", index: 900),
                Measurement(measurment: "901 V, no matter", index: 901),
                Measurement(measurment: "902 V, no matter", index: 902),
                Measurement(measurment: "903 V, no matter", index: 903),
                Measurement(measurment: "904 V, no matter", index: 904),
                Measurement(measurment: "905 V, no matter", index: 905),
                Measurement(measurment: "906 V, no matter", index: 906),
                Measurement(measurment: "907 V, no matter", index: 907),
                Measurement(measurment: "908 V, no matter", index: 908),
                Measurement(measurment: "909 V, no matter", index: 909),
                Measurement(measurment: "910 V, no matter", index: 910),
                Measurement(measurment: "911 V, no matter", index: 911),
                Measurement(measurment: "912 V, no matter", index: 912),
                Measurement(measurment: "913 V, no matter", index: 913),
                Measurement(measurment: "914 V, no matter", index: 914),
                Measurement(measurment: "915 V, no matter", index: 915),
                Measurement(measurment: "916 V, no matter", index: 916),
                Measurement(measurment: "917 V, no matter", index: 917),
                Measurement(measurment: "918 V, no matter", index: 918),
                Measurement(measurment: "919 V, no matter", index: 919),
                Measurement(measurment: "920 V, no matter", index: 920),
                Measurement(measurment: "921 V, no matter", index: 921),
                Measurement(measurment: "922 V, no matter", index: 922),
                Measurement(measurment: "923 V, no matter", index: 923),
                Measurement(measurment: "924 V, no matter", index: 924),
                Measurement(measurment: "925 V, no matter", index: 925),
                Measurement(measurment: "926 V, no matter", index: 926),
                Measurement(measurment: "927 V, no matter", index: 927),
                Measurement(measurment: "928 V, no matter", index: 928),
                Measurement(measurment: "929 V, no matter", index: 929),
                Measurement(measurment: "930 V, no matter", index: 930),
                Measurement(measurment: "931 V, no matter", index: 931),
                Measurement(measurment: "932 V, no matter", index: 932),
                Measurement(measurment: "933 V, no matter", index: 933),
                Measurement(measurment: "934 V, no matter", index: 934),
                Measurement(measurment: "935 V, no matter", index: 935),
                Measurement(measurment: "936 V, no matter", index: 936),
                Measurement(measurment: "937 V, no matter", index: 937),
                Measurement(measurment: "938 V, no matter", index: 938),
                Measurement(measurment: "939 V, no matter", index: 939),
                Measurement(measurment: "940 V, no matter", index: 940),
                Measurement(measurment: "941 V, no matter", index: 941),
                Measurement(measurment: "942 V, no matter", index: 942),
                Measurement(measurment: "943 V, no matter", index: 943),
                Measurement(measurment: "944 V, no matter", index: 944),
                Measurement(measurment: "945 V, no matter", index: 945),
                Measurement(measurment: "946 V, no matter", index: 946),
                Measurement(measurment: "947 V, no matter", index: 947),
                Measurement(measurment: "948 V, no matter", index: 948),
                Measurement(measurment: "949 V, no matter", index: 949),
                Measurement(measurment: "950 V, no matter", index: 950),
                Measurement(measurment: "951 V, no matter", index: 951),
                Measurement(measurment: "952 V, no matter", index: 952),
                Measurement(measurment: "953 V, no matter", index: 953),
                Measurement(measurment: "954 V, no matter", index: 954),
                Measurement(measurment: "955 V, no matter", index: 955),
                Measurement(measurment: "956 V, no matter", index: 956),
                Measurement(measurment: "957 V, no matter", index: 957),
                Measurement(measurment: "958 V, no matter", index: 958),
                Measurement(measurment: "959 V, no matter", index: 959),
                Measurement(measurment: "960 V, no matter", index: 960),
                Measurement(measurment: "961 V, no matter", index: 961),
                Measurement(measurment: "962 V, no matter", index: 962),
                Measurement(measurment: "963 V, no matter", index: 963),
                Measurement(measurment: "964 V, no matter", index: 964),
                Measurement(measurment: "965 V, no matter", index: 965),
                Measurement(measurment: "966 V, no matter", index: 966),
                Measurement(measurment: "967 V, no matter", index: 967),
                Measurement(measurment: "968 V, no matter", index: 968),
                Measurement(measurment: "969 V, no matter", index: 969),
                Measurement(measurment: "970 V, no matter", index: 970),
                Measurement(measurment: "971 V, no matter", index: 971),
                Measurement(measurment: "972 V, no matter", index: 972),
                Measurement(measurment: "973 V, no matter", index: 973),
                Measurement(measurment: "974 V, no matter", index: 974),
                Measurement(measurment: "975 V, no matter", index: 975),
                Measurement(measurment: "976 V, no matter", index: 976),
                Measurement(measurment: "977 V, no matter", index: 977),
                Measurement(measurment: "978 V, no matter", index: 978),
                Measurement(measurment: "979 V, no matter", index: 979),
                Measurement(measurment: "980 V, no matter", index: 980),
                Measurement(measurment: "981 V, no matter", index: 981),
                Measurement(measurment: "982 V, no matter", index: 982),
                Measurement(measurment: "983 V, no matter", index: 983),
                Measurement(measurment: "984 V, no matter", index: 984),
                Measurement(measurment: "985 V, no matter", index: 985),
                Measurement(measurment: "986 V, no matter", index: 986),
                Measurement(measurment: "987 V, no matter", index: 987),
                Measurement(measurment: "988 V, no matter", index: 988),
                Measurement(measurment: "989 V, no matter", index: 989),
                Measurement(measurment: "990 V, no matter", index: 990),
                Measurement(measurment: "991 V, no matter", index: 991),
                Measurement(measurment: "992 V, no matter", index: 992),
                Measurement(measurment: "993 V, no matter", index: 993),
                Measurement(measurment: "994 V, no matter", index: 994),
                Measurement(measurment: "995 V, no matter", index: 995),
                Measurement(measurment: "996 V, no matter", index: 996),
                Measurement(measurment: "997 V, no matter", index: 997),
                Measurement(measurment: "998 V, no matter", index: 998),
                Measurement(measurment: "999 V, no matter", index: 999),
                Measurement(measurment: "1000 V, no matter", index: 1000)


    ]
    // 1000 штук
    
    var myData: [Measurement] = [Measurement(measurment: "0 V, no matter", index: 0),
                                 Measurement(measurment: "1 V, no matter", index: 1),
                                 Measurement(measurment: "2 V, no matter", index: 2),
                                 Measurement(measurment: "3 V, no matter", index: 3),
                                 Measurement(measurment: "4 V, no matter", index: 4),
                                 Measurement(measurment: "5 V, no matter", index: 5),
                                 Measurement(measurment: "6 V, no matter", index: 6),
                                 Measurement(measurment: "7 V, no matter", index: 7),
                                 Measurement(measurment: "8 V, no matter", index: 8),
                                 Measurement(measurment: "9 V, no matter", index: 9),
                                 Measurement(measurment: "10 V, no matter", index: 10),
                                 Measurement(measurment: "11 V, no matter", index: 11),
                                 Measurement(measurment: "12 V, no matter", index: 12),
                                 Measurement(measurment: "13 V, no matter", index: 13),
                                 Measurement(measurment: "14 V, no matter", index: 14),
                                 Measurement(measurment: "15 V, no matter", index: 15),
                                 Measurement(measurment: "16 V, no matter", index: 16),
                                 Measurement(measurment: "17 V, no matter", index: 17),
                                 Measurement(measurment: "18 V, no matter", index: 18),
                                 Measurement(measurment: "19 V, no matter", index: 19),
                                 Measurement(measurment: "20 V, no matter", index: 20),
                                 Measurement(measurment: "21 V, no matter", index: 21),
                                 Measurement(measurment: "22 V, no matter", index: 22),
                                 Measurement(measurment: "23 V, no matter", index: 23),
                                 Measurement(measurment: "24 V, no matter", index: 24),
                                 Measurement(measurment: "25 V, no matter", index: 25),
                                 Measurement(measurment: "26 V, no matter", index: 26),
                                 Measurement(measurment: "27 V, no matter", index: 27),
                                 Measurement(measurment: "28 V, no matter", index: 28),
                                 Measurement(measurment: "29 V, no matter", index: 29),
                                 Measurement(measurment: "30 V, no matter", index: 30),
                                 Measurement(measurment: "31 V, no matter", index: 31),
                                 Measurement(measurment: "32 V, no matter", index: 32),
                                 Measurement(measurment: "33 V, no matter", index: 33),
                                 Measurement(measurment: "34 V, no matter", index: 34),
                                 Measurement(measurment: "35 V, no matter", index: 35),
                                 Measurement(measurment: "36 V, no matter", index: 36),
                                 Measurement(measurment: "37 V, no matter", index: 37),
                                 Measurement(measurment: "38 V, no matter", index: 38),
                                 Measurement(measurment: "39 V, no matter", index: 39),
                                 Measurement(measurment: "40 V, no matter", index: 40),
                                 Measurement(measurment: "41 V, no matter", index: 41),
                                 Measurement(measurment: "42 V, no matter", index: 42),
                                 Measurement(measurment: "43 V, no matter", index: 43),
                                 Measurement(measurment: "44 V, no matter", index: 44),
                                 Measurement(measurment: "45 V, no matter", index: 45),
                                 Measurement(measurment: "46 V, no matter", index: 46),
                                 Measurement(measurment: "47 V, no matter", index: 47),
                                 Measurement(measurment: "48 V, no matter", index: 48),
                                 Measurement(measurment: "49 V, no matter", index: 49),
                                 Measurement(measurment: "50 V, no matter", index: 50)
    ]
    
    var isPaginating = false
    
    func updateData(oldData: [Measurement], pagination: Bool = false, in direction: Direction, completion: @escaping (Result<[Measurement], Error>) -> () ) {
        
        if pagination {
            isPaginating = true
        }
        
        DispatchQueue.global(qos: .userInitiated).asyncAfter(deadline: .now() + 1) {
           //TODO: зачем original data нужна...
            // TODO: клетки нажимаются, убрать
            let originalData = [Measurement(measurment: "DEFAULT", index: 0)]
            var newData = [Measurement]()
            
            newData = self.updateData(direction: direction, oldData: oldData)
            self.myData = newData
            completion(.success(pagination ? newData : originalData))
            // TODO: обработать неуспех, то есть если не подгрузится из сети
            // TODO: обработать что выше 0 нельзя идти, не высвечивается худур и не обновляется и не срабатывают никакие методы
            if pagination {
                self.isPaginating = false
            }
        }
    }
    
    private func updateData(direction: Direction, oldData: [Measurement]) -> [Measurement]  {
        //запросить данные по актуальному индексу
         
//        либо вверх дата либо вниз
        let lastIndex = (direction == .down) ? (oldData.last ?? Measurement(measurment: "no", index: 0)).index : (oldData.first ?? Measurement(measurment: "no", index: 0)).index
//        или первый index
        let newData = (direction == .down) ? updateMeasurement(from: lastIndex + 1, in: direction) : updateMeasurement(from: lastIndex - 1, in: direction)
        // и нужное количество штук
        // в ответ получаю новые данные которые наползают куском на старые
        switch direction {
        case .up:
            var resultData = oldData
            for i in stride(from: C.delta, through: 0, by: -1) {
                resultData.insert(newData[i], at: 0)
                
            }
            resultData.removeSubrange((resultData.count - 1) - C.delta...(resultData.count - 1))
            print("up")
            
            return resultData
            
        case .down:
            var resultData = oldData
            for i in 0...C.delta {
                resultData.append(newData[i])
            }
            resultData.removeSubrange(0...C.delta)
            print("down")
            
            return resultData
            
        }
    }
}
